# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thika'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1230, 875)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 1221, 871))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/bg2.jpg"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/bg2.jpg")
        self.label.setMovie(self.movie)
        self.movie.start()
        
        
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 320, 701, 441))
        self.label_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border: 0px;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/7LP8.gif"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/7LP8.gif")
        self.label_3.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(264, 565, 221, 161))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/percent.gif"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/percent.gif")
        self.label_4.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 190, 271, 231))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/scene_044.gif"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/scene_044.gif")
        self.label_5.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1070, 90, 141, 91))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/AI-brain.jpg"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/AI-brain.jpg")
        self.label_7.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(960, 560, 251, 201))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/futuristic.jpg"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/futuristic.jpg")
        self.label_8.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(390, 10, 311, 121))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame10.jpg"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame10.jpg")
        self.label_9.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(400, 10, 281, 121))
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png")
        self.label_10.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, -10, 381, 191))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame1_flip.png"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame1_flip.png")
        self.label_2.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(44, 40, 311, 91))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/loading.gif"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/loading.gif")
        self.label_11.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(14, 430, 261, 361))
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame10.jpg"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame10.jpg")
        self.label_12.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(44, 475, 211, 281))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/hack.webp"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/hack.webp")
        self.label_13.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 790, 231, 81))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png")
        self.label_14.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(260, 790, 231, 81))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png")
        self.label_15.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(1030, 0, 191, 81))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png")
        self.label_16.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(740, 790, 231, 81))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png")
        self.label_17.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(990, 790, 231, 81))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png")
        self.label_18.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(1010, 180, 211, 251))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame10.jpg"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame10.jpg")
        self.label_19.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(710, 10, 311, 121))
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame10.jpg"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame10.jpg")
        self.label_20.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(940, 430, 281, 111))
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame10.jpg"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/frame10.jpg")
        self.label_21.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_21.setScaledContents(True)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(1030, 60, 191, 151))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/IMAGES/fram1.png"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png")
        self.label_22.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(730, 20, 271, 91))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/brain-signals.jpg"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/brain-signals.jpg")
        self.label_6.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(300, 140, 691, 241))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png")
        self.label_23.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(960, 440, 241, 91))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/all-hack.webp"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/all-hack.webp")
        self.label_24.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(1050, 20, 151, 41))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(340, 200, 591, 121))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/lines1.gif"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/lines1.gif")
        self.label_25.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(510, 790, 231, 81))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/fram1.png")
        self.label_26.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber_2.setGeometry(QtCore.QRect(740, 30, 111, 71))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(430, 40, 221, 51))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(720, 585, 241, 151))
        self.label_27.setText("")
        self.label_27.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/jarvis-iron-man-gif-2.gif"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/jarvis-iron-man-gif-2.gif")
        self.label_27.setMovie(self.movie)
        self.movie.start()


        self.label_27.setScaledContents(True)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(1020, 200, 191, 191))
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/coding.gif"))

        self.movie = QtGui.QMovie("C:/Users/felix/Videos/PYTHON PROJECS/IMAGES/coding.gif")
        self.label_28.setMovie(self.movie)
        self.movie.start()
        
        
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
# import MAIN_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
